// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz26pG-Gdeb-QRpwYRgHaSbWYhym_CBEI',
    appId: '1:530959351616:web:adb5fac29fb2f4454644a5',
    messagingSenderId: '530959351616',
    projectId: 'proyecto-final-234ce',
    authDomain: 'proyecto-final-234ce.firebaseapp.com',
    storageBucket: 'proyecto-final-234ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnK3eMW9ofaAahYFqvMiaFtMYRJFrUD8',
    appId: '1:530959351616:android:9b695ddb2aa173814644a5',
    messagingSenderId: '530959351616',
    projectId: 'proyecto-final-234ce',
    storageBucket: 'proyecto-final-234ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmwQ97wWlilpjWiPu0v-9RH3LLomlbEk',
    appId: '1:530959351616:ios:c6e90f82f6f370334644a5',
    messagingSenderId: '530959351616',
    projectId: 'proyecto-final-234ce',
    storageBucket: 'proyecto-final-234ce.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal2dam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUmwQ97wWlilpjWiPu0v-9RH3LLomlbEk',
    appId: '1:530959351616:ios:c6e90f82f6f370334644a5',
    messagingSenderId: '530959351616',
    projectId: 'proyecto-final-234ce',
    storageBucket: 'proyecto-final-234ce.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal2dam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz26pG-Gdeb-QRpwYRgHaSbWYhym_CBEI',
    appId: '1:530959351616:web:cde62fdb307d8c714644a5',
    messagingSenderId: '530959351616',
    projectId: 'proyecto-final-234ce',
    authDomain: 'proyecto-final-234ce.firebaseapp.com',
    storageBucket: 'proyecto-final-234ce.firebasestorage.app',
  );
}
